### ISSUE TITLE
File->Delete

### ISSUE THREAD

**Issue by ZhiKosta** [BTCGPU/electrum#24]
![03-26-2018croppercapture 3](https://user-images.githubusercontent.com/33158037/37897260-78fb2ac6-30ee-11e8-8e85-088f529d64bb.png)

Title format
(Isn't it safer to have this option removed? If someone really wants to delete his wallet file he should do it manually. This way you wont have accidental deletions)

**Comment by wilsonmeier** [comment]
Regarding the title: 
The title is generate by QT. But i agree, it looks bad. I will change it to a fixed string.

Regarding wallet deletion:
The user should be able to delete it from the UI without messing around in the filesystem and accidentally delete/corrupt more then just one wallet.
But i agree that a single "Question" dialog is not enough to show the importance of this decision.
I will change the icon to an exclamation mark and add a second dialog as a security layer.
