### ISSUE TITLE
Block Sync with server

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/electrum#3]
Sync is working now and is using variable header size and offset calculation. Compression of blockheader file needs to be reworked as gzip truncates the file. We need compression otherwise it will not be lightweight anymore.

`swap_with_parent` needs to be tested and eventually reworked.

**Comment by qasimsaleem1** [comment]
Waiting for its launch?
Release its beta or full version.

**Comment by wilsonmeier** [comment]
`swap_with_parent` has been reworked and will be merged with upcoming PR.

Header file compression will be delayed after network upgrade.

**Comment by wilsonmeier** [comment]
Fixed by 4f310149645e3ac5f62b039cf661fc8585841ef6
