### ISSUE TITLE
Slow blockchain header syncing

### ISSUE THREAD

**Issue by h4x3rotab** [BTCGPU/electrum#31]
Before the syncing is done, Electrum can only show transaction but not the confirmation number (always 0 confirmation). This can confuse users a lot.

To check if the header syncing is finished, click the green light at the right-bottom of the window and check the blockchain size & server height:

![image](https://user-images.githubusercontent.com/1343470/38051326-89cb95ac-3300-11e8-97a5-0e0ee7fd45ed.png)

To fix this, we need both:

1. A good indicator of syncing in progress
2. A compressed checkpoint file with all the headers

**Comment by wilsonmeier** [comment]
1. Indicator is in place (will come with next PR)
2. Compressed blockchain header file download will be implemented next.

**Comment by wilsonmeier** [comment]
> Compressed blockchain header file download will be implemented next.
It's implemented an will be merged with the upcoming PR

**Comment by wilsonmeier** [comment]
Fixed by 7f5f7e859e434df4b130a899cba64a59065f8661
