### ISSUE TITLE
Electrum startup issue

### ISSUE THREAD

**Issue by qasimsaleem1** [BTCGPU/electrum#32]
I have downloaded electrum portable 
But when i close and start it again it doesn't start

And when it start it takes lot of time and memory

**Comment by h4x3rotab** [comment]
Hi! What’s your Windows version? Does it start for the first time? If yes, can you try to restart the computer and try again?

**Comment by MentalNomad** [comment]
Also, are you sure you're closing it? In the Windows Beta, choosing File-Close actually only minimizes it to the tray. The ways to really end it are to right-click on the tray icon and choose "Exit ElectrumG" or to rick-click on it in the task bar and hit the X. (Hitting the X on the actual window only minimizes it.)

If you weren't closing it, you can't start it again. This behavior needs to be clarified in the production version.

**Comment by wilsonmeier** [comment]
BTW, there is also an option in the settings menu to revert to the default behavior.
Since the last comment is 2 months old this issue will be treated as resolved.
Feel free to re-open.
