### ISSUE TITLE
Unsigned Transaction save/export error

### ISSUE THREAD

**Issue by dickieminton** [BTCGPU/electrum#33]
Unsigned transactions created in a watching only wallet are saved (exported) with the input values missing. So transactions can not be signed offline! In effect cold storage doesn't work.

When attempting to sign Error message : ! "Value"

**Comment by dickieminton** [comment]
![btg_transaction](https://user-images.githubusercontent.com/38160490/38456840-cb3653e2-3a80-11e8-8566-f447f3314e28.png)

**Comment by h4x3rotab** [comment]
Legacy P2PKH Bitcoin addressees don’t need the amount to be signed. However this is not true for BIP143 style sighash. It won’t work Iif Electrum tries to read the amount from an transaction exported without the amount.

We should check how Electrum handles SegWit tx and always turn on BIP143 when exporting tx.
