### ISSUE TITLE
TREZOR support broken

### ISSUE THREAD

**Issue by prusnak** [BTCGPU/electrum#40]
There should be a string "Bgold" instead of "BitcoinGold" here: https://github.com/BTCGPU/electrum/blob/4d69492782d1017ab50c8449cef44570191a486b/plugins/trezor/trezor.py#L178

**Comment by wilsonmeier** [comment]
Thx for reporting, but the current master doesn't support HW wallets at all. Support for HW Wallets will be changed in the next version i'm working on.
