### ISSUE TITLE
Is this wallet still maintained to keep BTG?

### ISSUE THREAD

**Issue by dev-bre** [BTCGPU/electrum#57]
I see the last commit was over 3 years ago, while the original Electrum repo is constantly being updated.

Is this still a valid and reliable wallet to keep BTG coins?

**Comment by MentalNomad** [comment]
Yes, version 3.2.1 continues to be valid and reliable.

The new branch is based on 4.0, which will bring multiple new features, as well as properly implementing Hardware Wallet support.
